package org.atomiteam.jdbi.generic.dao;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.h2.H2DatabasePlugin;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class AtomiCompatibilityTest {

    private Jdbi jdbi;
    private AtomiPojoDao dao;

    @BeforeEach
    void setUp() {
        jdbi = Jdbi.create("jdbc:h2:mem:atomi_compat;DB_CLOSE_DELAY=-1;database_to_upper=false");
        jdbi.installPlugin(new H2DatabasePlugin());
        jdbi.useHandle(handle -> {
            handle.execute("DROP TABLE IF EXISTS atomi_pojo");
            handle.execute("CREATE TABLE atomi_pojo (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "display_name VARCHAR(255), " +
                    "account_id BIGINT, " +
                    "active BOOLEAN)");
        });
        dao = new AtomiPojoDao(jdbi);
    }

    @Test
    void plainPojoDoesNotNeedPersistenceBaseClass() {
        AtomiPojo item = new AtomiPojo();
        item.setDisplayName("Atomi");
        item.setAccountId(77L);
        item.setActive(Boolean.TRUE);

        AtomiPojo inserted = dao.insert(item);

        assertEquals(item, inserted);
        assertNotNull(item.getId());

        AtomiPojo loaded = dao.getById(item.getId()).orElseThrow();
        assertEquals(item.getId(), loaded.getId());
        assertEquals("Atomi", loaded.getDisplayName());
        assertEquals(77L, loaded.getAccountId());
        assertTrue(loaded.getActive());
    }

    @Test
    void generatedLongIdIsAssignedBackToPojo() {
        AtomiPojo first = create("First", 1L);
        AtomiPojo second = create("Second", 1L);

        dao.insert(first);
        dao.insert(second);

        assertNotNull(first.getId());
        assertNotNull(second.getId());
        assertTrue(second.getId() > first.getId());
    }

    @Test
    void manuallyAssignedLongIdStillWorks() {
        AtomiPojo item = create("Manual", 2L);
        item.setId(9001L);

        dao.insert(item);

        assertEquals(9001L, dao.getById(9001L).orElseThrow().getId());
    }

    @Test
    void mapGetAndListUseJavaPropertyNamesWithSnakeCaseDatabaseColumns() {
        AtomiPojo first = create("One", 10L);
        AtomiPojo second = create("Two", 10L);
        AtomiPojo third = create("Three", 20L);
        dao.insert(first);
        dao.insert(second);
        dao.insert(third);

        Map<String, Object> byName = new LinkedHashMap<>();
        byName.put("displayName", "Two");
        assertEquals(second.getId(), dao.get(byName).orElseThrow().getId());

        Map<String, Object> byAccount = new LinkedHashMap<>();
        byAccount.put("accountId", 10L);
        List<AtomiPojo> accountItems = dao.list(byAccount);
        assertEquals(2, accountItems.size());
    }

    @Test
    void updateAndReturnKeepsAtomiStyleEntityFlow() {
        AtomiPojo item = create("Before", 30L);
        dao.insert(item);

        AtomiPojo patch = new AtomiPojo();
        patch.setId(item.getId());
        patch.setDisplayName("After");

        AtomiPojo returned = dao.updateAndReturn(patch);

        assertEquals(patch, returned);
        AtomiPojo loaded = dao.getById(item.getId()).orElseThrow();
        assertEquals("After", loaded.getDisplayName());
        assertEquals(30L, loaded.getAccountId());
    }

    @Test
    void deleteAcceptsEntityOrId() {
        AtomiPojo byEntity = create("Entity Delete", 40L);
        AtomiPojo byId = create("Id Delete", 40L);
        dao.insert(byEntity);
        dao.insert(byId);

        assertEquals(1, dao.delete(byEntity));
        assertFalse(dao.getById(byEntity.getId()).isPresent());

        assertEquals(1, dao.delete(byId.getId()));
        assertFalse(dao.getById(byId.getId()).isPresent());
    }

    @Test
    void filterCountAndSortingWorkForPlainPojo() {
        dao.insert(create("C", 50L));
        dao.insert(create("A", 50L));
        dao.insert(create("B", 60L));

        assertEquals(2, dao.count(Filtering.create().eq("accountId", 50L)));

        List<AtomiPojo> sorted = dao.filter(Filtering.create()
                .withSorting("displayName", Sorting.ASC));
        assertEquals("A", sorted.get(0).getDisplayName());
        assertEquals("B", sorted.get(1).getDisplayName());
        assertEquals("C", sorted.get(2).getDisplayName());
    }

    private AtomiPojo create(String name, Long accountId) {
        AtomiPojo item = new AtomiPojo();
        item.setDisplayName(name);
        item.setAccountId(accountId);
        item.setActive(Boolean.TRUE);
        return item;
    }
}
